[2024-03-17T13:15:01.257+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_data_processing.read_from_postgres scheduled__2024-03-17T13:10:00+00:00 [queued]>
[2024-03-17T13:15:01.266+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_data_processing.read_from_postgres scheduled__2024-03-17T13:10:00+00:00 [queued]>
[2024-03-17T13:15:01.267+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-17T13:15:01.280+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): read_from_postgres> on 2024-03-17 13:10:00+00:00
[2024-03-17T13:15:01.287+0000] {standard_task_runner.py:60} INFO - Started process 217 to run task
[2024-03-17T13:15:01.290+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'postgres_data_processing', 'read_from_postgres', 'scheduled__2024-03-17T13:10:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/etl1.py', '--cfg-path', '/tmp/tmpazfm33ec']
[2024-03-17T13:15:01.292+0000] {standard_task_runner.py:88} INFO - Job 33: Subtask read_from_postgres
[2024-03-17T13:15:01.351+0000] {task_command.py:423} INFO - Running <TaskInstance: postgres_data_processing.read_from_postgres scheduled__2024-03-17T13:10:00+00:00 [running]> on host 6cb0e4687a92
[2024-03-17T13:15:01.429+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_data_processing' AIRFLOW_CTX_TASK_ID='read_from_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-03-17T13:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-17T13:10:00+00:00'
[2024-03-17T13:15:01.431+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl1.py", line 20, in read_from_postgres
    conn = connect_to_postgres()
  File "/opt/airflow/dags/etl1.py", line 9, in connect_to_postgres
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

[2024-03-17T13:15:01.445+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=postgres_data_processing, task_id=read_from_postgres, execution_date=20240317T131000, start_date=20240317T131501, end_date=20240317T131501
[2024-03-17T13:15:01.460+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 33 for task read_from_postgres (connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
; 217)
[2024-03-17T13:15:01.505+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-17T13:15:01.526+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
